[package]
name = "m1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.9.2"
embedded-graphics = "0.7.1"
cortex-a = "7.0.0"
tock-registers = "0.7.0"
