[package]
name = "p1c0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
m1 = { path = "../m1" }
embedded-graphics = "0.7.1"
tinybmp = "0.3.1"

[build-dependencies]
cc = "1.0"
