[package]
name = "p1c0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
emulator = ["arm-semihosting"]
default = []

[dependencies]
m1 = { path = "../m1" }
embedded-graphics = "0.7.1"
tinybmp = "0.3.1"
cortex-a = "7.0.0"
tock-registers = "0.7.0"
arm-semihosting = { path = "../arm_semihosting", optional = true, features = ["alloc"]}

[build-dependencies]
cc = "1.0"
