name: p1c0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cargo_clippy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: .github/workflows/setup.sh
    - uses: hermitcore/toolchain@downstream
    - name: Run cargo fmt check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: Run cargo clippy
      run: cargo xtask clippy

  cargo_test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: hermitcore/toolchain@downstream
    - name: Install dependencies
      run: .github/workflows/setup.sh
    - name: Run cargo test
      run: cargo xtask test

  cargo_build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: hermitcore/toolchain@downstream
    - name: Install dependencies
      run: .github/workflows/setup.sh
    - name: Build macho target
      run: cargo xtask build --release
    - name: Build binary target
      run: cargo xtask build --release --binary

  cargo_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: hermitcore/toolchain@downstream
    - name: Install dependencies
      run: .github/workflows/setup.sh
    - name: Run cargo xtask coverage
      run: cargo xtask coverage
    - uses: actions/upload-artifact@v3
      with:
        name: Coverage Report
        path: coverage_report
